import {
    Shield,
    Filter,
    Plane,
    Smartphone,
    Luggage,
    Search,
    User,
    ShoppingCart,
} from 'lucide-react';
export const insuranceProducts = [
    {
        id: '1',
        type: 'Travel',
        name: 'Flight Delay Insurance',
        summary: '$2/day, $100 payout',
        icon: { component: Plane, props: { className: "w-12 h-12 text-blue-500" } },
        riskLevel: 2,
        dailyRate: 2,
        payoutAmount: 100,
    },
    {
        id: '2',
        type: 'Electronics',
        name: 'Smartphone Protection',
        summary: '$5/month, $500 coverage',
        icon: { component: Smartphone, props: { className: "w-12 h-12 text-green-500" } },
        riskLevel: 3,
        dailyRate: 5,
        payoutAmount: 500,
    },
    {
        id: '3',
        type: 'Luggage',
        name: 'Baggage Loss Cover',
        summary: '$3/day, $750 payout',
        icon: { component: Luggage, props: { className: "w-12 h-12 text-purple-500" } },
        riskLevel: 4,
        dailyRate: 3,
        payoutAmount: 750,
    },
    {
        id: '4',
        type: 'Travel',
        name: 'Trip Cancellation',
        summary: '$4/day, $1000 payout',
        icon: { component: Plane, props: { className: "w-12 h-12 text-red-500" } },
        riskLevel: 5,
        dailyRate: 4,
        payoutAmount: 1000,
    },
    {
        id: '5',
        type: 'Electronics',
        name: 'Laptop Insurance',
        summary: '$6/month, $1500 coverage',
        icon: { component: Smartphone, props: { className: "w-12 h-12 text-indigo-500" } },
        riskLevel: 3,
        dailyRate: 6,
        payoutAmount: 1500,
    },
    {
        id: '6',
        type: 'Luggage',
        name: 'Luggage Delay Protection',
        summary: '$2/day, $250 payout',
        icon: { component: Luggage, props: { className: "w-12 h-12 text-orange-500" } },
        riskLevel: 2,
        dailyRate: 2,
        payoutAmount: 250,
    }
];