import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider, useTheme } from "@/contextProviders/ThemeProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}

// // Sample Component (For Testing Theme Usage)
// const SampleComponent = () => {
//   const { colors, tailwindClasses, typography } = useTheme();

//   return (
//     <div className={`${tailwindClasses.backgroundLight} p-6`}>
//       <h1 className={`${typography.headings} ${tailwindClasses.primary}`}>
//         Welcome!
//       </h1>
//       <p className={`${typography.body} ${tailwindClasses.textMuted}`}>
//         This is a sample component using the theme.
//       </p>
//     </div>
//   );
// };
